// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface PlayerCell: UITableViewCell
@end

@interface PlayerDetailsViewController: UITableViewController

@property IBOutlet UITextField * nameTextField;
@property IBOutlet UILabel * detailLabel;

-(IBAction) viewDidLoad;
-(IBAction) init;
-(IBAction) done:(id) sender;
-(IBAction) cancel:(id) sender;

@end

@interface PlayersViewController: UITableViewController
-(IBAction) init;
-(IBAction) viewDidLoad;
-(IBAction) playerDetailsViewControllerDidCancel:(id) controller;
-(IBAction) didAddPlayer:(id) player;

@end

@interface Player: NSObject
-(IBAction) initialize;

@end

