// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation PlayerCell
@end

@implementation PlayerDetailsViewController
@end

@implementation PlayersViewController
@end

@implementation Player
@end

